modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="radbuck_currency"
version="1.0.0"
displayName="RadBuck Currency"
displayURL="https://radikahn.com"
credits="Radikahn"
authors="Radikahn"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.radbuck_currency]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration